# Generated by Django 3.1.1 on 2020-09-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('usuario', models.CharField(max_length=45)),
                ('contrasenia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=240)),
                ('persona_id_persona', models.ForeignKey(db_column='PERSONA_id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='preguntas.persona')),
                ('pregunta_id_pregunta', models.ForeignKey(db_column='PREGUNTA_id_pregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='preguntas.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='usuario_id_usuario',
            field=models.ForeignKey(db_column='USUARIO_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='preguntas.usuario'),
        ),
    ]
